### ISSUE TITLE
Add toggle for centered section  titles

### ISSUE THREAD

**Issue by tlienart** [tlienart/PkgPage.jl#10]
could be a nice global toggle to add.

**Comment by zdroid** [comment]
Even though that looks like a bad design in the current layout, it's kinda easy so why not.

Adding `text-center` class to h2 in section command, if global var `section_title_centered` is true should work. Is that what you had in mind?

**Comment by tlienart** [comment]
I agree it’s not ideal, just looking at flux ML.ai and thinking about what people might want. Also jump.dev is insightful

**Comment by tlienart** [comment]
I agree it’s not ideal, just looking at flux ML.ai and thinking about what people might want. Also jump.dev is insightful
