### ISSUE TITLE
Docs is not clickable

### ISSUE THREAD

**Issue by Roger-luo** [tlienart/PkgPage.jl#23]
I created a package page for my package here: https://rogerluo.me/Comonicon.jl/

but somehow when I set

```
@def add_docs  = true
@def docs_url  = "https://rogerluo.me/Comonicon.jl/dev/"
```

the `Docs` cannot be clicked, tho when I inspect the actual link the href is set to https://rogerluo.me/Comonicon.jl/dev/ any idea how to fix this?

**Comment by Roger-luo** [comment]
It seems can be fixed if I disable the logo. The LOGO span somehow is too large and it covers the package name and the `Docs`

**Comment by tlienart** [comment]
Thanks for the report! so can I summarise the issue as follows:

- if there's a top-nav logo + docs button; the docs button is not clickable
- the likely culprit is that the `navbar-brand` span for the top-nav logo is too wide

@zdroid would you mind having a look at this one? thanks!!

**Comment by zdroid** [comment]
This is also an issue with PkgPage.jl's page, since "PkgPage.jl" can't be clicked.

The problem is that we were using `navbar-brand` incorrectly: https://getbootstrap.com/docs/4.5/components/navbar/#supported-content. I suggest we best move Docs out of navbar-brand and put it maybe on the right side?.

**Comment by tlienart** [comment]
> since "PkgPage.jl" can't be clicked.

is this a browser issue? I have no problem clicking it. 

> I suggest we move Docs out of navbar-brand and put it maybe on the right side?

sounds good, would you mind opening a PR with this? thanks! 🙏

**Comment by zdroid** [comment]
You can click it, but only on 10px of its right side. After that, you can't.

I'll send a fix soon. :smile:

**Comment by tlienart** [comment]
@Roger-luo this should be fixed & released (thanks Zlatan!) let us know if you still have an issue

**Comment by Roger-luo** [comment]
Thanks for the quick fix!
