### ISSUE TITLE
purgecss is somehow broken

### ISSUE THREAD

**Issue by Roger-luo** [tlienart/PkgPage.jl#31]
https://github.com/tlienart/PkgPage.jl/blob/0c63b04935a8b4b33dc7b88a27ea40fd6eda46ee/src/instantiate.jl#L111

I just realize that it seems when installing this package via `npm` it seems the `bin` becomes `purgecss.js` rather than `purgecss` now, which cause the depoly CI currently broken.

**Comment by tlienart** [comment]
thanks for noticing this!
