### ISSUE TITLE
Remove header

### ISSUE THREAD

**Issue by KristofferC** [tlienart/PkgPage.jl#34]
I don't see a `@def user_header` in the config file (maybe it doesn't exist yet). It would be useful for me since I think the header adds a bit too much "fluff" to a small package. I rather have the content more directly.

**Comment by tlienart** [comment]
That's a pretty easy one, I'll bring this in in a few mins

**Comment by tlienart** [comment]
ok there's now a `use_header` which you can set to `false`

**Comment by KristofferC** [comment]
<3
