### ISSUE TITLE
Code block always included

### ISSUE THREAD

**Issue by jebej** [tlienart/PkgPage.jl#35]
It seems like the output of a code block is always included in the html page, and using the Franklin `\textoutput{}` directive just ends up including the output twice.

I wanted to use the manual directive because I need to print raw html using `~~~` . 

Note that the `~~~` is actually not taken into account in the forced output, and so will print with the code tags regardless. If the `~~~` was respected I would not need to use `\textoutput{}`.

This is what it looks like, the three tildes plus some empty lines (since I only have `<script>` tags in there):
![image](https://user-images.githubusercontent.com/11141558/95025760-168b8e00-065a-11eb-9fbf-21d5377dba57.png)

**Comment by tlienart** [comment]
> It seems like the output of a code block is always included in the html page, and using the Franklin `\textoutput{}` directive just ends up including the output twice.

Please set `showall = false` at the end of the `config.md` to disable this (and then you do need to use `textoutput` explicitly whenever you want to)

If you want to **show** raw HTML then you need to use triple backticks + `html` so

`````
```html
<script> ... </script>
```
`````

if you want to have HTML being used in your page (like loading a special lib or whatever), then you do need to use `~~~` but not within a code block.

I'm not exactly sure I have replied to your second point, if so, can you please give me some more info about what output you're hoping to have?

**Comment by jebej** [comment]
`showall` did the trick. You have answered my question, thanks!
