### ISSUE TITLE
Footer should be placed at bottom and be as wide as the screen

### ISSUE THREAD

**Issue by fredrikekre** [tlienart/PkgPage.jl#37]
Looking e.g. at https://kristofferc.github.io/LazilyInitializedFields.jl/ it looks like the footer is part of the content rather than beeing a footer.

**Comment by tlienart** [comment]
I saw that too, I need to check how Kristoffer did it bc on the demo page it spreads across as expected: https://tlienart.github.io/PkgPage.jl/

**Comment by fredrikekre** [comment]
Damnit, I explicitly asked if he had modified it before opening an issue :D

**Comment by KristofferC** [comment]
I'm sorry... 

![image](https://user-images.githubusercontent.com/1282691/95086670-0db1bf80-0721-11eb-8a3f-63eb6b01b149.png)

**Comment by tlienart** [comment]
Seems this is fixed as per https://kristofferc.github.io/LazilyInitializedFields.jl/#other_methods closing
